version: '3'

services:
  cl-inter:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "200"
    ports:
      - "8080:8080"
